config/routes.rb
GameDemo::Application.routes.draw do
  get "login" => "session#new"
  post "login" => "session#create"
  get "logout" => "session#destroy"

  get "games/index"

  resources :gamers #TODO restrict to create
  resources :games do #TODO restrict to create, index, show, vote
    put :vote, :as => :vote_for, :on => :member
  end

  root :to => "games#index"

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :description, :title

  belongs_to :contributor, :class_name => Gamer.name
  has_many :votes

  validates_presence_of :title
  validates_uniqueness_of :title
  validates_length_of :title, :maximum => 100

  def avg_rank
    self.votes.average(:rank)
  end
end

app/models/gamer.rb
class Gamer < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :votes

  validates_presence_of :username
  validates_presence_of :password, :on => :creation
  validates_confirmation_of :password, :on => :creation
  validates_uniqueness_of :username

  attr_accessible

  #TODO db indexes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :gamer
  belongs_to :game

  validates_inclusion_of :rank, :in => 1..5
  #validates_uniqueness_of :gamer_id, :scope => :game_id

  attr_accessible
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gamers_controller.rb
class GamersController < ApplicationController
  def create
    @gamer = Gamer.new
    @gamer.password = params[:gamer][:password]
    @gamer.password_confirmation = params[:gamer][:password_confirmation]
    @gamer.email = params[:gamer][:email]
    @gamer.username = params[:gamer][:username]
    @gamer.save!
    reset_session # protect from session fixation attacks;
    auto_login(@gamer)
    redirect_back_or_to root_url, :notice => "Created!"
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :find_game, :only => [:show, :vote]

  def index
  end

  def new
    @game = Game.new
  end

  #TODO restrict to logged in
  def create
    @game = Game.new params[:game]
    @game.contributor = current_user
    @game.save!
    redirect_to games_url
  end

  def show
    @vote_by_user = (current_user and @game.votes.where(:gamer_id => current_user.id).first)
  end

  def vote
    vote_ = @game.votes.where(:gamer_id => current_user.id).first_or_initialize
    vote_.rank = params[:rank]
    vote_.save
    render :json => {:status => :ok}
  end

  protected

  def find_game
    @game = Game.find params[:id]
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    @gamer = Gamer.new
  end

  def create
    @gamer = login(params[:session][:username], params[:session][:password])
    if @gamer
      redirect_back_or_to root_url, :notice => "Signed in!"
    else
      @gamer = Gamer.new
      flash.now.alert = "Username or password was invalid"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def voter game
    links = (1..5).map do |n|
      link_to "X", "#", "data-remote-url" => vote_for_game_url(game), "data-rank" => n, :class => "vote #{'current_rank' if @vote_by_user and @vote_by_user.rank >= n}"
    end
    content_tag(:span, links.join.html_safe, :class => "votes #{'voted_by_user' if @vote_by_user}")
  end
end

app/views/games/index.html.haml
%h1 Games
%ol
  - Game.all.each do |game|
    %li= link_to game.title, game
%p
  = link_to "create new game", new_game_url

app/views/games/new.html.haml
%h1 Create new game
= form_for @game do |f|
  %p
    = f.label :title
    = f.text_field :title
  %p
    = f.label :description
    = f.text_area :description
  %p
    = submit_tag "Create"

app/views/games/show.html.haml
%h1= @game.title
%p= @game.description
%p
  Vote:
  = voter(@game)
  (avg. #{@game.avg_rank}, #{@game.votes.length} votes)
%p
  =link_to "List games", games_url

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "UTF-8"}
    %title  Game demo.
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #top_bar
      - if current_user
        You are signed in as
        = current_user.username
        = link_to "sign out", logout_path
      - else
        You are not signed in
        = link_to "change that", login_path
    #notice= notice
    #alert= alert
    #content
      = yield
    #footer
      = raw "&copy;" * 20

app/views/session/new.html.haml
= form_for :session do |f|
  %h1 Do you have an account already?
  %p
    = f.label :username
    = f.text_field :username
  %p
    = f.label :password
    = f.password_field :password
  %p
    = submit_tag "Sign in"

= form_for @gamer do |f|
  %h1 Or not?
  %p
    = f.label :username
    = f.text_field :username
  %p
    = f.label :email
    = f.email_field :email
  %p
    = f.label :password
    = f.password_field :password
  %p
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  %p
    = submit_tag "Sign up"